MovieNewMVC/Controllers/Api/CustomersController.cs
using AutoMapper;
using MovieNewMVC.Dtos;
using MovieNewMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Data.Entity;

namespace MovieNewMVC.Controllers.Api
{
    public class CustomersController : ApiController
    {
        private ApplicationDbContext _contaxt;
        public CustomersController()
        {
            _contaxt = new ApplicationDbContext();
        }
        //GET /api/customers
        //public IEnumerable<Customer> GetCustomers()
        public IEnumerable<CustomerDto> GetCustomers()
        {
            //return _contaxt.Customers.ToList();
            return _contaxt.Customers.Include(c => c.MembershipType).ToList().Select(Mapper.Map<Customer, CustomerDto>);
        }
        //GET /api/customers/1
        //public Customer GetCustomer(int id)
        public CustomerDto GetCustomer(int id)
        {
            //var customer = _contaxt.Customers.SingleOrDefault(c => c.Id == id);
            var customer = _contaxt.Customers.Include(c => c.MembershipType).SingleOrDefault(c => c.Id == id);

            if (customer == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);
            //return customer;
            return Mapper.Map<Customer, CustomerDto>(customer); // change return type to CustomerDto 
        }
        // POST /api/customers
        [HttpPost]
        // change Customer to CustomerDto
        public CustomerDto CreateCustomer(CustomerDto customerDto)
        {
            if (!ModelState.IsValid)
                throw new HttpResponseException(HttpStatusCode.BadRequest);
            var customer = Mapper.Map<CustomerDto,Customer>(customerDto)    ;
            _contaxt.Customers.Add(customer); // now this customer object has an ID that is generated by the database   
            _contaxt.SaveChanges();

            // we want to add this ID in our DTO and return it to the client 
            customerDto.Id = customer.Id; 

            return customerDto;
        }
        // PUT /api/customers/1
        [HttpPut]
        //public void UpdateCustomer(int id, Customer customer)
        public void UpdateCustomer(int id, CustomerDto customerDto)
        {
            if (!ModelState.IsValid)
                throw new HttpResponseException(HttpStatusCode.BadRequest);
            var custInDb = _contaxt.Customers.SingleOrDefault(c => c.Id == id);
            if (custInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            // use mapper
            Mapper.Map<CustomerDto ,Customer>(customerDto, custInDb);
            
            //custInDb.Name = customerDto.Name; // change customer to customerDto
            //custInDb.Birthdate = customerDto.Birthdate;
            //custInDb.MembershipId = customerDto.MembershipId;
            //custInDb.IsSunscribedToNewsletter = customerDto.IsSunscribedToNewsletter;

            _contaxt.SaveChanges();

        }
        // DELETE /api/customers/1
        [HttpDelete]
        public void DeleteCustomer(int id)
        {
            var custInDb = _contaxt.Customers.SingleOrDefault(c => c.Id == id);
            if (custInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);
            _contaxt.Customers.Remove(custInDb);
            _contaxt.SaveChanges();
        }
    }
}

MovieNewMVC/Controllers/Api/MoviesController.cs
using MovieNewMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace MovieNewMVC.Controllers.Api
{
    public class MoviesController : ApiController
    {
        private ApplicationDbContext _context;
        public MoviesController()
        {
            _context = new ApplicationDbContext();
        }
        // GET /api/movies
        public IEnumerable<Movie> GetMovies()
        {
            return _context.Movies.ToList();
        }
        // GET /api/movies/1
        public Movie GetMovie(int id)
        {
            var movie = _context.Movies.SingleOrDefault(m => m.Id == id);
            if (movie == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);
            return movie;
        }  
        //POST /api/movies/
        [HttpPost]
        public Movie CreateMovie(Movie movie)
        {
            if (!ModelState.IsValid)
                throw new HttpResponseException(HttpStatusCode.BadRequest);
            _context.Movies.Add(movie);
            _context.SaveChanges();
            return movie;
        }
        //PUT /api/movies/1
        [HttpPut]
        public void UpdateCustomer(int id, Movie movie)
        {
            if (!ModelState.IsValid)
                throw new HttpResponseException(HttpStatusCode.BadRequest);
            var movieInDb = _context.Movies.SingleOrDefault(m => m.Id == id);
            if (movieInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);
            movieInDb.Name = movie.Name;
            movieInDb.ReleaseDate = movie.ReleaseDate;
            movieInDb.NoInStock = movie.NoInStock;
            movieInDb.DateAdded = movie.DateAdded;
            movieInDb.GenreId = movie.GenreId;
            _context.SaveChanges();
        }
        // DELETE /api/movies/1
        [HttpDelete]
        public void DeleteMovie(int id)
        {
            var movieInDb = _context.Movies.SingleOrDefault(m => m.Id == id);
            if (movieInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);
            _context.Movies.Remove(movieInDb);
            _context.SaveChanges();
        }
    }
}

MovieNewMVC/Controllers/PointsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieNewMVC.Controllers
{
    public class PointsController : Controller
    {
        // GET: Points
        public ActionResult Index()
        {
            //string[] texts = System.IO.File.ReadAllLines(Server.MapPath("~/Points/BirthDateLabel.txt"));
            //ViewBag.Data = texts;
            //return View();
            string path = "~/Points/BirthDateLabel.txt";
            Console.WriteLine ("path = " + path);
            return View();
            //return File
            //return File(Stream, "text/plain",path);
            //return File("~/Points/BirthDateLabel.txt", "text/plain", "Birthdate.pdf");
            //return File("~/Points/BirthDateLabel.txt");
        }
    }
}

MovieNewMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Movie Rental Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("_Navbar");
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")*@
    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)
</body>
</html>

MovieNewMVC/Views/Shared/_Navbar.cshtml
<div class="navbar navbar-dark navbar-fixed-top border-danger">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Movie Rental App", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Customer", "Index", "Customers")</li>
                <li>@Html.ActionLink("Movie", "Index", "Movies")</li>
                <li>@Html.ActionLink("Point", "Index", "Points")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>